### ISSUE TITLE
Initalized MediatR handlers are null with Structuremap on Azure

### ISSUE THREAD

**Issue by EliiseS** [jbogard/MediatR#192]
I've got a strange issue that is eerily similar to [this post](https://github.com/jbogard/MediatR/issues/184), with the exception of the error message that is displayed. 

When deploy to Azure I get a null reference error, that I've managed to narrow down via trial and error to initializing MediatR handlers with StructureMap. I don't understand why this is happening or how to fix this, other than removing MediatR.

I'm using .Net Core with Entity Framework 4.7.

The full stack of the exception I get in Azure:
```
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type)
   at StructureMap.TypeRules.TypeExtensions.IsConcrete(Type type)
   at StructureMap.TypeRules.TypeExtensions.<rawFindInterfacesThatCloses>d__14.MoveNext()
   at StructureMap.TypeRules.TypeExtensions.<rawFindInterfacesThatCloses>d__14.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at StructureMap.Graph.GenericConnectionScanner.<ScanTypes>b__5_0(Type type)
   at StructureMap.StringExtensions.Each[T](IEnumerable`1 enumerable, Action`1 action)
   at StructureMap.Graph.GenericConnectionScanner.ScanTypes(TypeSet types, Registry registry)
   at StructureMap.Graph.AssemblyScanner.<>c__DisplayClass33_0.<ScanForTypes>b__2(IRegistrationConvention x)
   at StructureMap.StringExtensions.Each[T](IEnumerable`1 enumerable, Action`1 action)
   at StructureMap.Graph.AssemblyScanner.<ScanForTypes>b__33_1(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at StructureMap.PluginGraphBuilder.RunConfigurations()
   at StructureMap.PluginGraphBuilder.Build()
   at StructureMap.Container..ctor(Registry registry)
   at WebApplication1.Startup.ConfigureIoC(IServiceCollection services)
   at WebApplication1.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type)
   at StructureMap.TypeRules.TypeExtensions.IsConcrete(Type type)
   at StructureMap.TypeRules.TypeExtensions.<rawFindInterfacesThatCloses>d__14.MoveNext()
   at StructureMap.TypeRules.TypeExtensions.<rawFindInterfacesThatCloses>d__14.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at StructureMap.Graph.GenericConnectionScanner.<ScanTypes>b__5_0(Type type)
   at StructureMap.StringExtensions.Each[T](IEnumerable`1 enumerable, Action`1 action)
   at StructureMap.Graph.GenericConnectionScanner.ScanTypes(TypeSet types, Registry registry)
   at StructureMap.Graph.AssemblyScanner.<>c__DisplayClass33_0.<ScanForTypes>b__2(IRegistrationConvention x)
   at StructureMap.StringExtensions.Each[T](IEnumerable`1 enumerable, Action`1 action)
   at StructureMap.Graph.AssemblyScanner.<ScanForTypes>b__33_1(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```
- ASP.NET Core 1.1.2 w/ .NET 4.7
- Azure Web App
- MediatR 3.0.1
- StructureMap.Microsoft.DependencyInjection 1.3.1
- StructureMap 4.5.2
- NLog.Web.AspNetCore 4.4.1

The full project that I've created to test this issue can be found at: [https://github.com/EliiseS/BlockingDeployment/](https://github.com/EliiseS/BlockingDeployment/)
To recreate, deploy above repo to Azure.

The class below with `x.ConnectImplementationsToTypesClosing(typeof({HandlerName}Handler<>));` cause the exception to be thrown.

```
using MediatR;
using StructureMap;

namespace WebHost.IoC
{
    public class RuntimeRegistry : Registry
    {
        public RuntimeRegistry()
        {
            Scan(x =>
            {
                x.Assembly(GetType().Assembly);

                //Below section of code causes the issue with deploying (Any one of these)
                x.ConnectImplementationsToTypesClosing(typeof(IRequestHandler<>)); // Handlers with no response
                x.ConnectImplementationsToTypesClosing(typeof(IRequestHandler<,>)); // Handlers with a response
                x.ConnectImplementationsToTypesClosing(typeof(IAsyncRequestHandler<>)); // Async handlers with no response
                x.ConnectImplementationsToTypesClosing(typeof(IAsyncRequestHandler<,>)); // Async Handlers with a response
                x.ConnectImplementationsToTypesClosing(typeof(INotificationHandler<>));
                x.ConnectImplementationsToTypesClosing(typeof(IAsyncNotificationHandler<>));
                // End of the section causing the issue

                x.AssembliesAndExecutablesFromApplicationBaseDirectory();
                x.TheCallingAssembly();
                x.LookForRegistries();
                x.WithDefaultConventions();
            });

            //Setting up MediatR
            For<SingleInstanceFactory>().Use<SingleInstanceFactory>(ctx => t => ctx.GetInstance(t));
            For<MultiInstanceFactory>().Use<MultiInstanceFactory>(ctx => t => ctx.GetAllInstances(t));
            For<IMediator>().Use<Mediator>();
        }
    }
}
```

If there's any information missing, please let me know.

**Comment by EliiseS** [comment]
Updating to .Net Core 2.0 fixes the problem, whatever that problem might have been.
If anyone ever figures out why, feel free to let me know.
