### ISSUE TITLE
Noisy Stack Traces with an Exception Above IRequestHandler

### ISSUE THREAD

**Issue by eddiemacb** [jbogard/MediatR#234]
Thanks for this package. It took some time to convince my peers but everybody loves it now for cleaning up controllers and dramatically increasing the testability of our MVC projects.

We are using Mediatr v2.0.2 and what I have noticed in our logs is that the stack traces are excessively long with a lot of duplicated information when we have an exception in code called from `IRequestHandler`. Here is an example:

```
2018-02-08 12:09:40,490 [1372] ERROR CustomExceptionHandler - Message Id: da201a6d-e898-4bab-b91c-9f90b8f62fd3
Corporate.Grs.Services.Common.CustomException.AlreadyExistsException: The account attached to this token is already active.
   at Member.Handlers.TokenValidationHandler.CheckMemberUnregistered(String token)
   at Member.Handlers.TokenValidationHandler.Handle(TokenValidationQuery query)
   at MediatR.Internal.RequestHandlerWrapper`2.Handle(IRequest`1 message)
   at MediatR.Mediator.Send[TResponse](IRequest`1 request)
   at Member.Controllers.MemberController.MemberValidation(CommonHeaders headers, TokenIdentifiers identifiers)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Corporate.Grs.Services.Common.Infrastructure.HttpHeaderInterceptor.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()
```

Is it something we are doing in our usage of the API that is causing the stack traces to go beyond the following?

```
2018-02-08 12:09:40,490 [1372] ERROR CustomExceptionHandler - Message Id: da201a6d-e898-4bab-b91c-9f90b8f62fd3
Corporate.Grs.Services.Common.CustomException.AlreadyExistsException: The account attached to this token is already active.
   at Member.Handlers.TokenValidationHandler.CheckMemberUnregistered(String token)
   at Member.Handlers.TokenValidationHandler.Handle(TokenValidationQuery query)
   at MediatR.Internal.RequestHandlerWrapper`2.Handle(IRequest`1 message)
   at MediatR.Mediator.Send[TResponse](IRequest`1 request)
   at Member.Controllers.MemberController.MemberValidation(CommonHeaders headers, TokenIdentifiers identifiers)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
```

Or, has this been fixed in Mediatr 3.x or 4.x? I don't see it called out in the Releases but maybe it wasn't an important enough commit/fix for you to mention it there.

Thanks.

**Comment by jbogard** [comment]
No it's just the nature of async. This is getting fixed in the .NET Framework however!

**Comment by eddiemacb** [comment]
Thanks for responding. Maybe I should find the issue in https://github.com/Microsoft/dotnet and upvote it.

**Comment by remcoros** [comment]
@eddiemacb It's already done and will be in .net core 2.1, here's a nice blog on it: https://www.ageofascent.com/2018/01/26/stack-trace-for-exceptions-in-dotnet-core-2.1/

**Comment by eddiemacb** [comment]
Thanks @remcoros!

That article was very technical but I get the point. Sadly, my services will be on .NET Framework for the foreseeable future and not sure how quickly the improvements will make it across. But, I may see if there are any quick wins in the commits that I can put into a temporary `StackTraceCleaner` class. If I simply treat it as text, I can probably make it shorter and readable but items like resolving generic type names is just not possible at that simple level.

**Comment by remcoros** [comment]
This is the issue on corefx: https://github.com/dotnet/corefx/issues/24627

And it's marked as 'netfx-port-consider', so who knows. It may be in .NET 4.7.xx or 4.8 if backported. Might want to +1 it :)

**Comment by eddiemacb** [comment]
Ha! I think @aelij has already done the work.

https://github.com/aelij/AsyncFriendlyStackTrace

I will start with his package and see how it helps our situation. Looks like it handles a lot of the noise.

**Comment by aelij** [comment]
You may also want to check out https://github.com/benaadams/Ben.Demystifier/ which also resolves lambdas, local functions, iterators, etc.

**Comment by eddiemacb** [comment]
Noted. Thanks for your recommendation. Ben's does seem to handle more scenarios in clean-up. The code I am trying to clean up does not use much of that _now_ but it would make sense to future-proof it.
