### ISSUE TITLE
Cannot resolve scoped service 'MediatR.IMediator' from root provider.

### ISSUE THREAD

**Issue by KeithBarrows** [jbogard/MediatR#240]
As a link that helps describe what we are running into:  [Forums on ServiceStack](https://forums.servicestack.net/t/cant-resolve-service-which-is-registered-at-net-core-ioc/4764/3)

I have an abstract base controller class that uses MediatR (4.0.1).  This class is inherited by each Core 2 API project we stand up.  It's purpose is to test/prove CRUD actions from UI to DB work.  However, we have a test class that tests to see if the DI container is setup correctly.  The test is written as:
```
    [TestFixture]
    public class DiContainerIntegrationTests
    {
        [Test]
        public void AppLoadsAndDiIsFullyConfigured()
        {
            var webHost = WebHost.CreateDefaultBuilder()
                .UseStartup<Startup>()
                .UseIISIntegration()
                .UseEnvironment("Development")
                .Build();

            var activatorCache = new TypeActivatorCache();

            //TODO: Figure out why we can't instantiate IMediator for ColorsController.

            var mvcAssembly = typeof(Startup).GetTypeInfo().Assembly;
            var controllers =
                from type in mvcAssembly.GetExportedTypes()
                where typeof(ApiControllerBase).IsAssignableFrom(type)
                where !type.IsAbstract
                where !type.IsGenericTypeDefinition
                where type.Name.EndsWith("Controller")
                    && type.Name != "ColorsController"  // <-- comment this line out and it fails!
                select type;
            
            foreach (var controller in controllers)
            {
                var instantiatedController = activatorCache.CreateInstance<ApiControllerBase>(webHost.Services, controller);
            }
        }
    }
```
The controller that is failing is:
```
    public class ColorsController : ColorsControllerBase
    {
        public ColorsController(IHostingEnvironment env, IConfiguration configuration, IMediator mediator) : base(env,
            configuration, mediator)
        {
        }
    }
```
Base classes in supporting project:
```
    [Produces("application/json")]
    [Route("api/Colors")]
    public abstract class ColorsControllerBase: ApiControllerBase
    {
        private readonly string _connectionStringName;

        protected ColorsControllerBase(IHostingEnvironment env
                                     , IConfiguration configuration = null
                                     , IMediator mediator = null
                                     , string connectionStringName = null) : base(env, configuration, mediator)
        {
            _connectionStringName = connectionStringName;
        }


        [HttpGet]
        public IActionResult Get()
        {
            var response = Mediator.Send(new QueryGet(_connectionStringName));
            return Ok(response.Result);
        }

        [HttpGet("{id}", Name = "Get")]
        public IActionResult Get(Guid id)
        {
            var response = Mediator.Send(new QueryGetById(id, _connectionStringName));
            return Ok(response.Result);
        }

        [HttpPost]
        public async Task<IActionResult> Post([FromBody]ColorModelBinding value)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var response = await Mediator.Send(new CommandPost(value, _connectionStringName));
            return Created("Get", new { id = response });
        }

        [HttpPut("{id}")]
        public IActionResult Put(Guid id, [FromBody]ColorModelBinding value)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            Mediator.Send(new CommandPut(id, value, _connectionStringName));
            return Ok();
        }

        [HttpDelete("{id}")]
        public IActionResult Delete(Guid id)
        {
            Mediator.Send(new CommandDelete(id, _connectionStringName));
            return Ok();
        }
    }

    public class ApiControllerBase : ControllerBase
    {
        public IHostingEnvironment Env { get; }
        public IConfiguration Configuration { get; set; }
        public IMediator Mediator { get; }

        public ApiControllerBase(IHostingEnvironment env)
        {
            Env = env ?? throw new ArgumentNullException(nameof(env));
        }
        public ApiControllerBase(IHostingEnvironment env, IConfiguration configuration, IMediator mediator)
        {
            Env = env ?? throw new ArgumentNullException(nameof(env));
            if (mediator != null)
                Mediator = mediator;
            if (configuration != null)
                Configuration = configuration;
        }
    }
```

The failure is:

> System.InvalidOperationException : Cannot resolve scoped service 'MediatR.IMediator' from root provider.
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, ServiceProvider serviceProvider)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
>    at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
>    at lambda_method(Closure , IServiceProvider , Object[] )
>    at Microsoft.AspNetCore.Mvc.Internal.TypeActivatorCache.CreateInstance[TInstance](IServiceProvider serviceProvider, Type implementationType)
>    at InnovAge.SupportiveHousing.WebApi.Test.DiContainerIntegrationTests.AppLoadsAndDiIsFullyConfigured() in E:\Workspaces\InnovAge\SupportiveHousing\BackEnd\Trunk\InnovAge.SupportiveHousing.WebApi.Test\DiContainerIntegrationTests.cs:line 42
> 

Thoughts?  Observations?

**Comment by jbogard** [comment]
IMediator is registered as scoped (see https://github.com/jbogard/MediatR.Extensions.Microsoft.DependencyInjection/blob/master/src/MediatR.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs#L268) so that means you must create a scope to resolve an IMediator. You'll need to get a scope provider first, then resolve your stuff (I put this all in a fixture class https://github.com/jbogard/ContosoUniversityDotNetCore/blob/master/ContosoUniversity.IntegrationTests/SliceFixture.cs )

**Comment by weitzhandler** [comment]
@jbogard you just helped in another non-related issue. I tried resolving a scoped service directly and it failed and couldn't figure out why.
Thank you!
