### ISSUE TITLE
Issue Registering a wrapped generic handler

### ISSUE THREAD

**Issue by oferns** [jbogard/MediatR#245]
Hi,

I have this request and handler  (dotnet core 2.0.5) Mediatr 4.0.1 SimpleInjector 4.0.12

```
 public class Email<T> : IRequest<string> where T : class {

        public Email(string view, EmailMetaData<T> metadata) {
            View = view;
            MetaData = metadata;
        }

        public string View { get; }
        public EmailMetaData<T> MetaData { get; }
    }


    public class EmailRequestHandler<T> : IRequestHandler<Email<T>, string> where T : class {
        private readonly IEmailClient client;
        private readonly ITemplateService templateService;

        public EmailRequestHandler(IEmailClient client, ITemplateService templateService) {
            this.client = client ?? throw new ArgumentNullException(nameof(client));
            this.templateService = templateService ?? throw new ArgumentNullException(nameof(templateService));
        }

        public async Task<string> Handle(Email<T> request, CancellationToken cancellationToken) {
            var html = await templateService.RenderTemplateAsync(request.View, request.MetaData.Model);
            return await client.Send(request.MetaData, html);
        }
    }
```

and I get this error when I call it (for example) like this

`var email = await mediator.Send(new Comms.Email<Identity.Register>("~/Register/EmailConfirmEmail.cshtml", emailOptions));                    
`

> SimpleInjector.ActivationException: No registration for type IRequestHandler<Email<Register>, String> could be found. Note that there exists a registration for a different type MediatR.IRequestHandler<TRequest, TResponse> while the requested type is MediatR.IRequestHandler`2[[LF.Comms.Email<LF.Comms.Email<LF.Identity.Register>, System.String>.
>    at SimpleInjector.Container.ThrowMissingInstanceProducerException(Type serviceType)
>    at SimpleInjector.Container.GetInstanceForRootType(Type serviceType)
>    at SimpleInjector.Container.GetInstance(Type serviceType)
>    at MediatR.Internal.RequestHandlerBase.GetHandler[THandler](SingleInstanceFactory factory)
>    --- End of inner exception stack trace ---
>    at MediatR.Internal.RequestHandlerBase.GetHandler[THandler](SingleInstanceFactory factory)
>    at MediatR.Internal.RequestHandlerWrapperImpl`2.<>c__DisplayClass0_0.<Handle>g__Handler0()
>    at MediatR.Internal.RequestHandlerWrapperImpl`2.Handle(IRequest`1 request, CancellationToken cancellationToken, SingleInstanceFactory singleFactory, MultiInstanceFactory multiFactory)
>    at MediatR.Mediator.Send[TResponse](IRequest`1 request, CancellationToken cancellationToken)
>    at LF.Mvc.Register.RegisterController.<Index>d__3.MoveNext() in D:\repos\someproject\LF.Mvc\Register\RegisterController.cs:line 40
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

Am I doing something wrong or is this unsupported or maybe I should be asking SimpleInjector?

**Comment by oferns** [comment]
Me being a dick. Sorry
