### ISSUE TITLE
Can't update to beta-004

### ISSUE THREAD

**Issue by Silv3rcircl3** [jbogard/MediatR#35]
Hi, i wanted to upgrade to beta-004 but reciving a strange error message from nuget. 
Upgrade to beta-002 is working fine, so I found a difference between the two versions.
In beta-004
![image](https://cloud.githubusercontent.com/assets/11612539/7269149/41c1abba-e8d1-11e4-8889-4738644ae36d.png)
In beta-002
![image](https://cloud.githubusercontent.com/assets/11612539/7269156/56f97dc8-e8d1-11e4-9fce-f59d3d5685f7.png)

Is this correct, the "Unsupported, Version=0.0" ?

I don't know if it's helpfull but here is the nuget error
![image](https://cloud.githubusercontent.com/assets/11612539/7269181/ac696b60-e8d1-11e4-94f5-33248be491e2.png)

>System.InvalidOperationException: Failed to add reference to 'System.Runtime'. Please make sure that it is in the Global Assembly Cache. ---> System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.
   at VSLangProj.References.Add(String bstrPath)
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.AddGacReference(String name)
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.AddFrameworkReference(String name)
   --- End of inner exception stack trace ---
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__d2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActions>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformAction>d__0.MoveNext()

**Comment by jbogard** [comment]
What NuGet version are you using?

**Comment by jbogard** [comment]
I think you might need to upgrade to NuGet 2.8.5 http://blog.nuget.org/20150331/nuget-2.8.5.html

**Comment by tawman** [comment]
FWIW, I installed *MediatR 2.0.0-beta-004* via package manager console in VS 2013 yesterday without issue into new solution.

```
C:\Program Files (x86)\Microsoft Visual Studio 12.0>nuget
NuGet Version: 2.8.50506.491
```

**Comment by Silv3rcircl3** [comment]
Sorry, totally missed this issue,I will try it again tomorrow or next week.
Was VS 2015 CTP 6, maybe it's fixed in the RC.

**Comment by Silv3rcircl3** [comment]
Isn't working in the RC with Nuget 3..
But as @tawman mentioned, it's a nuget error and not related to MediatR so forget about it ;-)

**Comment by eddiegroves** [comment]
I noticed that the reason 004 installs in VS2013 and doesn't get the same error as in VS2015 is that NuGet 2.8 is pulling 'Facade references' for System.Runtime, System.Threading.Tasks, System.Linq and System.Collections. Since these DLLs are GAC'd for 4.5.1 I believe it's safe to then remove the facade references from the project. Interesting behaviour...
