### ISSUE TITLE
Handler not found when using MediatR in .NET Core console app

### ISSUE THREAD

**Issue by t3hInox** [jbogard/MediatR#377]
Hi,

I have also created a question in SO: https://stackoverflow.com/questions/54874329/net-core-console-app-mediatr-command-handler-doesnt-get-called

Basically command handler is not found when I'm trying to use MediatR in .NET Core console app. I suspect it is DI related issue. The same logic works in ASP.NET Core app. I have also tried to remove all dependencies from the handler, but it didn't help.

I'm using Microsoft.Extensions.DependencyInjection.

Program.cs (DI):
`public class Program
    {
        static ManualResetEvent _quitEvent = new ManualResetEvent(false);

        static void Main(string[] args)
        {
            Console.WriteLine("Job Server started");

            //DI setup
            var serviceProvider = new ServiceCollection()
                .AddQuartz()
                .AddTransient<InitializeJobServer>()
                .AddTransient<ProcessAdRssFeedsJob>()
                .AddScoped<IConfigService, ConfigService>()
                .AddScoped<IRssService, RssService>()
                .AddScoped<IBaseService, BaseService>()                
                .AddDbContext<MyDbContext>(options =>
                    options.UseNpgsql("xxx"))
                .AddMemoryCache()
                .AddMediatR(new[] { typeof(ProcessAdSectionsRssCommand).GetType().Assembly, typeof(ProcessAdSectionsRssCommandHandler).GetType().Assembly })
                .BuildServiceProvider();

            Console.CancelKeyPress += (sender, eArgs) => {
                _quitEvent.Set();
                eArgs.Cancel = true;
            };

            Task.Run(async () =>
            {
                await serviceProvider.GetService<InitializeJobServer>().Start();
            });

            _quitEvent.WaitOne();
            Console.WriteLine("Job Server ended");
        }
    }`

Command + handler:
`public class ProcessAdSectionsRssCommand : IRequest<bool>
    {

        public class Handler : IRequestHandler<ProcessAdSectionsRssCommand, bool>
        {
            private readonly MyDbContext _context;
            private readonly IRssService _rssService;
            private readonly IConfigService _configService;

            public Handler(
                MyDbContext context,
                IRssService rssService,
                IConfigService configService)
            {
                _context = context;
                _rssService = rssService;
                _configService = configService;
            }

            public async Task<bool> Handle(ProcessAdSectionsRssCommand request, CancellationToken cancellationToken)
            {
                //Some long logic
                return true;
            }
        }
    }`

I'm getting exception:

System.InvalidOperationException: Handler was not found for request of type MediatR.IRequestHandler`2[xxx.Application.Rss.Commands.ProcessAdSectionsRss.ProcessAdSectionsRssCommand,System.Boolean]. Register your handlers with the container. See the samples in GitHub for examples.
   at MediatR.Internal.RequestHandlerBase.GetHandler[THandler](ServiceFactory factory)
   at MediatR.Internal.RequestHandlerWrapperImpl`2.<>c__DisplayClass0_0.<Handle>g__Handler|0()
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at xxx.Jobs.Jobs.ProcessAdRssFeedsJob.Execute(IJobExecutionContext context) in D:\xxx\Jobs\ProcessAdRssFeedsJob.cs:line 29

Versions:

- Mediatr version: 6.0.0
- .NET code SDK version: 2.2
- Microsoft DI version (Microsoft.Extensions.DependencyInjection): 2.2.0

I'll appreciate any tips. Thanks!

**Comment by t3hInox** [comment]
I managed to solve this issue. You can see the comments in the SO link I posted.
