### ISSUE TITLE
Error constructing handler when using Scoped lifetime

### ISSUE THREAD

**Issue by yehia2amer** [jbogard/MediatR#381]
**Problem**
Trying to use a library called [Sieve ](https://github.com/Biarity/Sieve) with MediatR, but it fail to be injected when using:
```services.AddScoped<ISieveProcessor, ApplicationSieveProcessor>();```
Although it is working probably when using:
```services.AddSingleton<ISieveProcessor>(new MySieveProcessor().GetSieve());```

**Expected Behaviour**
`ISieveProcessor` should be injected using **Scoped lifetime** properly in a class implementing `IRequestHandler`

**Exception Message**

```
Error constructing handler for request of type
MediatR.IRequestHandler 2[Northwind.Application.Products.Queries.GetAllProducts.GetAllProductsQuery,Northwind.Application.Products.Queries.GetAllProducts.ProductsListViewModel].
Register your handlers with the container. See the samples in GitHub for examples.
```

**StackTrace**

```
   at MediatR.Internal.RequestHandlerBase.GetHandler[THandler](ServiceFactory factory)
   at MediatR.Internal.RequestHandlerWrapperImpl`2.<>c__DisplayClass0_0.<Handle>g__Handler|0()
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at Northwind.Application.Infrastructure.RequestPerformanceBehaviour`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in C:\Users\amery\Desktop\MediatR CQRS & Sieve\NorthwindTraders-master\Northwind.Application\Infrastructure\RequestPerformanceBehaviour.cs:line 25
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at Northwind.WebUI.Controllers.ProductsController.GetAll(SieveModel sieveModel) in C:\Users\amery\Desktop\MediatR CQRS & Sieve\NorthwindTraders-master\Northwind.WebUI\Controllers\ProductsController.cs:line 21
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
```

**Example**
I Created This Gist that replicate the issue here:
[https://gist.github.com/yehia2amer/869984e1837b4683767035964aac680d](https://gist.github.com/yehia2amer/869984e1837b4683767035964aac680d)
This is based on [NorthwindTraders Sample](https://github.com/JasonGT/NorthwindTraders).

**Full Project Example**
[https://github.com/yehia2amer/NorthwindTraders_MediatR_Sieve](https://github.com/yehia2amer/NorthwindTraders_MediatR_Sieve)

**Comment by jbogard** [comment]
I'm now registering everything with Transient, so that should fix this.
