### ISSUE TITLE
InvalidCastException MediatR creates wrong request handler

### ISSUE THREAD

**Issue by dcarapic** [jbogard/MediatR#408]
I'm trying to use MediatR in my web project but I keep getting a very weird situation where I get the following error when trying to use the Send method:

	System.InvalidOperationException: Error constructing handler for request of type MediatR.IRequestHandler`2[OP.BR2.EntityCommon.GetEntitiesCommand`1[OP.BR2.Product.ProductViewEntity],OP.BR2.EntityCommon.GetEntitiesCommandResponse`1[OP.BR2.Product.ProductViewEntity]]. Register your handlers with the container. See the samples in GitHub for examples. ---> System.InvalidCastException: Unable to cast object of type 'OP.BR2.EntityCommon.GetEntityEditableObjectCommandHandler`1[OP.BR2.Product.ProductViewEntity]' to type 'MediatR.IRequestHandler`2[OP.BR2.EntityCommon.GetEntitiesCommand`1[OP.BR2.Product.ProductViewEntity],OP.BR2.EntityCommon.GetEntitiesCommandResponse`1[OP.BR2.Product.ProductViewEntity]]'.
	   at MediatR.ServiceFactoryExtensions.GetInstance[T](ServiceFactory factory)
	   at MediatR.Internal.RequestHandlerBase.GetHandler[THandler](ServiceFactory factory)
	   --- End of inner exception stack trace ---
	   at MediatR.Internal.RequestHandlerBase.GetHandler[THandler](ServiceFactory factory)
	   at MediatR.Internal.RequestHandlerWrapperImpl`2.<>c__DisplayClass0_0.<Handle>g__Handler|0()
	   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
	   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
	   at CallSite.Target(Closure , CallSite , Object )
	   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
	   at OP.BR2.Server.MainHub.Command(ICommand command) in C:\Work\Projects\OP\OP.BusinessRunner2\OP.BR2.Server\MainHub.cs:line 58
	   at lambda_method(Closure , Object )
	   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
	   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteHubMethod(ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments)
	   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.Invoke(HubMethodDescriptor descriptor, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamedInvocation)

I have two handlers for two different messages which do share common base class but everything else is otherwise unrelated. For some reason the Mediator instantiates wrong handler and tries to pass the wrong command object to it which causes the exception.

I've tried to create a separate project and to isolate the bug, but no mater what I try everything works fine in the second project. I simply can not reproduce it outside my project.
The really weird thing is that the all the commands/command responses/command handlers are in one namespace, however if I separate them into different namespaces (one set of command/command response/command handler into one namespace and the other into another) then everything works fine !??!

Can you give me some hints what I might be doing wrong? If necessary I can provide a test project but everything works nicely there. I am using LightInject as the container, I am not even sure that the container could be doing something wrong.

**Comment by dcarapic** [comment]
Ignore this issue. It seems to be lightinject issue.
