### ISSUE TITLE
Null reference exception in RequestHandlerWrapperImpl

### ISSUE THREAD

**Issue by CDargis** [jbogard/MediatR#438]
Hi there. We are currently experiencing intermittent object reference exceptions. Here are a few:

```
Message : Object reference not set to an instance of an object.
StackTrace :
   at MediatR.Internal.RequestHandlerWrapperImpl`2.<>c__DisplayClass0_1.<Handle>b__2()
   at WellRight.Platform.Microservices.MediatR.Pipeline.IdentityPipelineBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at WellRight.Platform.Microservices.MediatR.Pipeline.ValidationPipelineBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at WellRight.Platform.Microservices.MediatR.Pipeline.CatchAllPipelineBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
Type : System.NullReferenceException
```

```
Message : Object reference not set to an instance of an object.
StackTrace :
   at MediatR.Internal.RequestHandlerWrapperImpl`2.<>c__DisplayClass0_1.<Handle>b__2()
   at WellRight.Platform.Microservices.MediatR.Pipeline.ConcurrentRequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at WellRight.Platform.Microservices.MediatR.Pipeline.SequentialRequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at WellRight.Platform.Microservices.MediatR.Pipeline.IdentityPipelineBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at WellRight.Platform.Microservices.MediatR.Pipeline.ValidationPipelineBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at WellRight.Platform.Microservices.MediatR.Pipeline.CatchAllPipelineBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
Type : System.NullReferenceException
```

`MediatR` version 7.0.0
`Lamar.Microsoft.DependencyInjection version 3.1.0` 
We are using generic constraints. All of the above behaviors implement `IPipelineBehavior<,>`. One thing to note here is that every request should be passing through each behavior. It is odd that sometimes the request makes it through halfway through the pipeline behaviors and sometimes maybe 1/4 of the way through.

Any thoughts or insight as to what is going on here? After taking a look at the `RequestHandlerWrapperImpl` code I think that maybe our container is returning something null? Thanks in advance for any help.

**Comment by CDargis** [comment]
Ah one more thing. I mentioned this issue is intermittent. It seems to come on with greater load.

**Comment by CDargis** [comment]
So I pulled down the mediatr code and rewrote a bit for readability to debug locally. Definitely a null object coming back in the list of pipeline behaviors. Also really strange there is some duplicates.

![image](https://user-images.githubusercontent.com/2372977/64644075-73753000-d3d7-11e9-8b18-392cadf278a7.png)

**Comment by CDargis** [comment]
Our registration code:

```
public MediatRRegistry(string assemblyPrefix)
{
    Scan(_ =>
    {
        _.AssembliesFromApplicationBaseDirectory(x => 
            string.IsNullOrEmpty(assemblyPrefix) || x.FullName.StartsWith(assemblyPrefix));
        _.ConnectImplementationsToTypesClosing(typeof(IValidator<>));
        _.ConnectImplementationsToTypesClosing(typeof(IRequestHandler<>));
        _.ConnectImplementationsToTypesClosing(typeof(IRequestHandler<,>));
        _.ConnectImplementationsToTypesClosing(typeof(ISequentialRequestPreProcessor<>));
        _.ConnectImplementationsToTypesClosing(typeof(ISequentialRequestPostProcessor<,>));
        _.ConnectImplementationsToTypesClosing(typeof(IConcurrentRequestPreProcessor<>));
        _.ConnectImplementationsToTypesClosing(typeof(IConcurrentRequestPostProcessor<,>));
    });

    // Pipeline order of operation
    For(typeof(IPipelineBehavior<,>)).Add(typeof(CatchAllPipelineBehavior<,>));
    For(typeof(IPipelineBehavior<,>)).Add(typeof(ValidationPipelineBehavior<,>));
    For(typeof(IPipelineBehavior<,>)).Add(typeof(IdentityPipelineBehavior<,>));
    For(typeof(IPipelineBehavior<,>)).Add(typeof(ServiceIdentityPipelineBehavior<,>));
    For(typeof(IPipelineBehavior<,>)).Add(typeof(RequestLockPipelineBehavior<,>));
    For(typeof(IPipelineBehavior<,>)).Add(typeof(SequentialRequestPreProcessorBehavior<,>));
    For(typeof(IPipelineBehavior<,>)).Add(typeof(ConcurrentRequestPreProcessorBehavior<,>));
    For(typeof(IPipelineBehavior<,>)).Add(typeof(SequentialRequestPostProcessorBehavior<,>));
    For(typeof(IPipelineBehavior<,>)).Add(typeof(ConcurrentRequestPostProcessorBehavior<,>));

    For<IMediator>().Use<Mediator>().Transient();
    For<ServiceFactory>().Use(ctx => ctx.GetInstance);
}
```

Help us Obi-Wan.

**Comment by CDargis** [comment]
Probably related: https://github.com/JasperFx/lamar/issues/157

**Comment by jbogard** [comment]
Uhhhhhhh

No idea. You aren't using `services.AddMediatR`, right?

**Comment by CDargis** [comment]
No. Was not aware that existed.

**Comment by jbogard** [comment]
I have no idea about duplicates. You can check for sure by resolving the same pipeline directly from Lamar yourself:

https://github.com/jbogard/MediatR/blob/master/src/MediatR/Internal/RequestHandlerWrapper.cs#L57

What does this return for you?

**Comment by CDargis** [comment]
That is exactly the screenshot I posted. The code looks slightly different because I had to rewrite a bit to be able to debug at runtime.

It returns a list of 11 objects - one of which is null and there are several duplicates.

**Comment by CDargis** [comment]
Definitely a Lamar issue. Doesn't look like the issue is going to get much movement there. I can't think of any solutions in your end that don't involve providing a way for consumer to serve up the IEnumerable<> themselves.

**Comment by CDargis** [comment]
We could probably get something working by implementing a more complicated `ServiceFactory` but I think we are just going to use a different DI container.

**Comment by jorhar** [comment]
Moved back to StructureMap to resolve this issue.
