### ISSUE TITLE
Notification handler being called twice

### ISSUE THREAD

**Issue by OutstandingBillNeal** [jbogard/MediatR#501]
When I publish a notification, the handlers for that notification (there are two of them) are all called twice.  This is a problem because the handlers do things which should only be done once.  I'm pretty sure this is not the "accidental double registration problem" (see below).  The call stacks look interesting, because the second call's is different to the first's.

The first call ends up with a call stack like this

    FooHandler line 22
    [External Code]
    AsyncPrivateMethodInControllerWhichPublishesFooNotification
    [Resuming Async Method]
    [External Code]

The second call ends up with a call stack like this

    FooHandler line 22
    [External Code]

And some of the things FooHandler is trying to do don't work.

Here are the more detailed call stacks:

publish

	at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
	at System.Environment.get_StackTrace()
	at OurCompanyName.Web.Controllers.AuditController.<NotifyOfAuditCompletion>d__19.MoveNext() in C:\Git\nz\OurCompanyName.Web\Controllers\AuditController.cs:line 241
	at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
	at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass4_0.<OutputAsyncCausalityEvents>b__0()
	at System.Runtime.CompilerServices.TaskAwaiter.<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()
	at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
	at System.Threading.Tasks.Task.FinishContinuations()
	at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
	at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
	at OurCompanyName.Web.WebData.Audit.Repository.AuditRepository.<GetAudit>d__9.MoveNext() in C:\Git\nz\OurCompanyName.Web\WebData\Audit\Repository\AuditRepository.cs:line 245
	at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
	at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass4_0.<OutputAsyncCausalityEvents>b__0()
	at System.Runtime.CompilerServices.TaskAwaiter.<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()
	at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.<>c__DisplayClass6_0.<GetActionLogDelegate>b__0()
	at System.Web.Util.SynchronizationHelper.SafeWrapCallback(Action action)
	at System.Threading.Tasks.Task.Execute()
	at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
	at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
	at System.Threading.ThreadPoolWorkQueue.Dispatch()

handle first time

	at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
	at System.Environment.get_StackTrace()
	at OurCompanyName.Web.Mediator.Audit.OurCompanyNameAuditHardFail.CompleteAuditHandler_OurCompanyNameAuditHardFail.<Handle>d__2.MoveNext() in C:\Git\nz\OurCompanyName.Web\Mediator\Audit\OurCompanyNameAuditHardFail\CompleteAuditHandler_OurCompanyNameAuditHardFail.cs:line 22
	at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
	at OurCompanyName.Web.Mediator.Audit.OurCompanyNameAuditHardFail.CompleteAuditHandler_OurCompanyNameAuditHardFail.Handle(CompleteAudit notification, CancellationToken cancellationToken)
	at MediatR.Mediator.<PublishCore>d__7.MoveNext()
	at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
	at MediatR.Mediator.PublishCore(IEnumerable`1 allHandlers)
	at MediatR.Internal.NotificationHandlerWrapperImpl`1.Handle(INotification notification, CancellationToken cancellationToken, ServiceFactory serviceFactory, Func`2 publish)
	at MediatR.Mediator.PublishNotification(INotification notification, CancellationToken cancellationToken)
	at MediatR.Mediator.Publish[TNotification](TNotification notification, CancellationToken cancellationToken)
	at OurCompanyName.Web.Controllers.AuditController.<NotifyOfAuditCompletion>d__19.MoveNext() in C:\Git\nz\OurCompanyName.Web\Controllers\AuditController.cs:line 241
	at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
	at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass4_0.<OutputAsyncCausalityEvents>b__0()
	at System.Runtime.CompilerServices.TaskAwaiter.<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()
	at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
	at System.Threading.Tasks.Task.FinishContinuations()
	at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
	at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
	at OurCompanyName.Web.WebData.Audit.Repository.AuditRepository.<GetAudit>d__9.MoveNext() in C:\Git\nz\OurCompanyName.Web\WebData\Audit\Repository\AuditRepository.cs:line 245
	at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
	at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass4_0.<OutputAsyncCausalityEvents>b__0()
	at System.Runtime.CompilerServices.TaskAwaiter.<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()
	at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.<>c__DisplayClass6_0.<GetActionLogDelegate>b__0()
	at System.Web.Util.SynchronizationHelper.SafeWrapCallback(Action action)
	at System.Threading.Tasks.Task.Execute()
	at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
	at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
	at System.Threading.ThreadPoolWorkQueue.Dispatch()

handle second time

	at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
	at System.Environment.get_StackTrace()
	at OurCompanyName.Web.Mediator.Audit.OurCompanyNameAuditHardFail.CompleteAuditHandler_OurCompanyNameAuditHardFail.<Handle>d__2.MoveNext() in C:\Git\nz\OurCompanyName.Web\Mediator\Audit\OurCompanyNameAuditHardFail\CompleteAuditHandler_OurCompanyNameAuditHardFail.cs:line 22
	at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
	at OurCompanyName.Web.Mediator.Audit.OurCompanyNameAuditHardFail.CompleteAuditHandler_OurCompanyNameAuditHardFail.Handle(CompleteAudit notification, CancellationToken cancellationToken)
	at MediatR.Mediator.<PublishCore>d__7.MoveNext()
	at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
	at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass4_0.<OutputAsyncCausalityEvents>b__0()
	at System.Runtime.CompilerServices.TaskAwaiter.<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()
	at System.Threading.Tasks.AwaitTaskContinuation.ExecuteWorkItemHelper()
	at System.Threading.ThreadPoolWorkQueue.Dispatch()

This could be a real noob problem because I don't really understand how the Mediatr registration code works.

As far as I can see, I'm only registering Mediatr once.  I've tried the registration in a variety of ways, including in the way Jimmy described [here](https://github.com/jbogard/MediatR/blob/master/samples/MediatR.Examples.Autofac/Program.cs) (although I had to comment a bunch of it out to get it to build in my .NET4.7.2 solution).  All the different registration methods exhibited the same problem.  The simplest registration looks like this:

    builder
        .RegisterType<MediatR.Mediator>()
        .As<IMediator>()
        .InstancePerLifetimeScope();

    builder.Register<ServiceFactory>( // a colleague tell me this registers the handlers and messages
        context =>
        {
            var c = context.Resolve<IComponentContext>();
            return t => c.Resolve(t);
        });

**Comment by jbogard** [comment]
So the next thing I'd do is check what registrations Autofac has - is there some way to print that out?

**Comment by OutstandingBillNeal** [comment]
I couldn't find a way to print out the registrations, but I did find the cause of the problem.  We had two instances of this type of line, where the `MyType`s used were in the same assembly.

    builder.RegisterAssemblyTypes(typeof(MyType).Assembly).AsImplementedInterfaces().AsSelf();
