### ISSUE TITLE
Exception with RequestExceptionHandler

### ISSUE THREAD

**Issue by digitalsigi** [jbogard/MediatR#504]
Hi,
I am relatively new to MediatR but found the concept perfectly matching my current requirements.
I have already implemented a couple of handlers including some PipelineBehavior and want now to add Exception Handling. Doing so I got an Exception:

"The number of generic arguments provided doesn't equal the arity of the generic type definition. (Parameter 'instantiation')"

How to fix this?

Stacktrace:
`
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.GetExceptionHandlers(TRequest request, Type exceptionType, MethodInfo& handleMethodInfo)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.<Handle>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.<Handle>d__2.MoveNext()
`

My RequestExceptionHandler:

```
    public class AvsRequestExceptionHandler<TRequest,TResponse> : IRequestExceptionHandler<TRequest,TResponse>     
    {
        private readonly ILogger<AvsRequestExceptionHandler<TRequest, TResponse>> logger;

        public AvsRequestExceptionHandler(ILogger<AvsRequestExceptionHandler<TRequest,TResponse>> logger)
        {
            this.logger = logger;
        }

        public Task Handle(TRequest request, Exception exception, RequestExceptionHandlerState<TResponse> state, CancellationToken cancellationToken)
        {
            logger.LogError(exception, "{@state}\n{@request}", request);
            ((IAvsResponseBase)state.Response).Result = AvsWebResult.Failed(AvsWebError.GetError(AvsWebError.ErrorCode.ExceptionOccured, exception.Message));
            state.SetHandled();
            return Task.CompletedTask;
        }

    }
```

**Comment by joaomatossilva** [comment]
Can you try to inherit from the interface `IRequestExceptionHandler<in TRequest, TResponse, TException>` istead?

Both should be compatible, but I think this is a bug on how the MediatR.Extensions.Microsoft.DependencyInjection is actually discovering and register the services.
link [here](https://github.com/jbogard/MediatR.Extensions.Microsoft.DependencyInjection/pull/83): 

I think the service is trying to register the service, that on the concrete side only has 2 generic arguments but it's connecting to an interface with 3 parameters

**Comment by digitalsigi** [comment]
Thanks for looking into it.
Took me a step further, but I had to define the specific TRequest/TResponse pair and the expected Exception. That's not really handy when looking to my scenario with 20+ handlers. What I understood is, that you have already proposed a solution which should allow the generic two parameter approach. Correct?

**Comment by joaomatossilva** [comment]
No, my PR was about skipping the registration so that you can handle it yourself.

I think you'll be safe by just registering your `AvsRequestExceptionHandler` by implementing `IRequestExceptionHandler<TRequest,TResponse,TException>` instead like this:

```
public class AvsRequestExceptionHandler<TRequest,TResponse,TException> : IRequestExceptionHandler<TRequest,TResponse,TException>
    where TException : Exception
    {
        private readonly ILogger<AvsRequestExceptionHandler<TRequest, TResponse>> logger;

        public AvsRequestExceptionHandler(ILogger<AvsRequestExceptionHandler<TRequest,TResponse>> logger)
        {
            this.logger = logger;
        }

        public Task Handle(TRequest request, TException exception, RequestExceptionHandlerState<TResponse> state, CancellationToken cancellationToken)
        {
            //remaining of the class

```

Disclaimer: I wrote the code in here by heart, so it might be syntaticly incorrect

**Comment by digitalsigi** [comment]
Thanks again, you made my day!
I overlooked the TException constraint, added it an voila I worked.
