### ISSUE TITLE
INotificationHandler<T> where T is Interface does not handle publish calls

### ISSUE THREAD

**Issue by ArrowtheArcher** [jbogard/MediatR#545]
```
public class SubNotificationHandler : INotificationHandler<ISubNotification>
    {
        public async Task Handle(ISubNotification notification, CancellationToken cancellationToken)
        {
            //Do some
        }
    }

    public class NotificationHandler : INotificationHandler<Notification>
    {
        public async Task Handle(Notification notification, CancellationToken cancellationToken)
        {
             //Do some
        }
    }
```
I was trying to do something like this and on publish both Handle methods are called but if NotificationHandler does not exist then SubNotificationHandler.Handler is not called. Is there any way to fix this without creating an empty NotificationHandler? (Notification class is an implementation of ISubNotification)

**Comment by lilasquared** [comment]
what is the relationship between `Notification` and `ISubNotification`?

**Comment by lilasquared** [comment]
I think you actually need to do it as a constrained generic but dotnet core DI does not support this by default I don't think

**Comment by ArrowtheArcher** [comment]
Their relationship
```
    public class Notification : ISubNotification
    {
        public string Par { get; set; }

        public Notification(string par)
        {
            Par = par;
        }
    }

    public interface ISubNotification : INotification
    {
        string Par { get; set; }
    }
```
I tried constrained generic(if I am not mistaking) like this
`
public class SubNotificationHandler<T> : INotificationHandler<T> where T: ISubNotification
`
and it did help this case but I later encountered a problem. When I try to publish a notification that is not an implementation of ISubNotification I am getting this error
<hr>
System.ArgumentException: GenericArguments[0], 'Mediator_Test.Shared.SecondNotification', on 'Mediator_Test.Shared.SubNotificationHandler`1[T]' violates the constraint of type 'T'.
 ---> System.TypeLoadException: GenericArguments[0], 'Mediator_Test.Shared.SecondNotification', on 'Mediator_Test.Shared.SubNotificationHandler`1[T]' violates the constraint of type parameter 'T'.
   at System.RuntimeTypeHandle.Instantiate(Type[] inst)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   --- End of inner exception stack trace ---
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at MediatR.ServiceFactoryExtensions.GetInstances[T](ServiceFactory factory)
   at MediatR.Internal.NotificationHandlerWrapperImpl`1.Handle(INotification notification, CancellationToken cancellationToken, ServiceFactory serviceFactory, Func`4 publish)
   at MediatR.Mediator.PublishNotification(INotification notification, CancellationToken cancellationToken)
   at MediatR.Mediator.Publish[TNotification](TNotification notification, CancellationToken cancellationToken)
   at Mediator_Test.Server.Controllers.TargetController.Index() in C:\Users\Nadir_A\source\repos\Mediator Test\Mediator Test\Server\Controllers\TargetController.cs:line 27
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()

**Comment by lilasquared** [comment]
So if you're using dotnet core the built in DI does not support constrained generics as I mentioned above.  You will need to implement a different DI like Lamar.

**Comment by jbogard** [comment]
Feel free to upvote this PR:

https://github.com/dotnet/runtime/pull/39540

That adds constrained generics support to the built-in DI container.

**Comment by MPapst** [comment]
Same for requests. I am struggling with this with Generic Requests.
Even with .NET 5.0 RC1 where the PR should be included.

Only if I add a transient on my own per 
`services.AddTransient<IRequestHandler<GenericRequest, string>, GenericHandler>();`
when manually adding it like this
`services.AddTransient<IRequestHandler<IRequest<string>, string>, GenericHandler>();`
its not working with an exception (no handler found).

**Comment by MPapst** [comment]
@lilasquared the purpose is to extend functionality over a messaging solution.
The handled requests would be limited to a certain subset that is triggering a background operation (e.g. `ITaskCreatingCommand : IRequest<TaskCreatedResponse>` or similar). 
Having multiple handlers for the same requests is nothing I intend to do.

I already thought about a PipelineBehavior, but that would then lead to a `NullRequestHandler<TRequest>` registered for every those requests.
So currently I am going with registering the handlers by hand and I'm not sure if I should stay with that, just because of the issues that could be upcoming when having multiple handlers matching a IRequest.

**Comment by lilasquared** [comment]
Having multiple handers for the same request might not be the intention but it could be the outcome.  Given that you could register multiple how would the mediator determine which is the right one?  Each request should have a handler.  I'm not sure I understand the purpose enough to know why you would need a `NullRequestHandler<TRequest>` for each one.  Even so, creating an abstract `NullRequestHandler<TRequest>` and then concrete `SomeHandler : NullRequestHandler<SomeRequest>` will prevent manual registration and any accidental handlers matching multiple request types.

**Comment by MPapst** [comment]
Having multiple handlers that match a single request can always happen. 
But you are right, having it on an Interface could be unintended.

Having an abstract base class is exactly what I try to avoid, because it leads to a lot of dead classes and duplicate code.
Imagine you need to use DI on the abstract class to have a repository or an IOptions<T> available. You will need to have a constructor in your every implementation calling the base constructor to inject the object.
So having a Generic Implementation for that would be more handy - but can lead to unexpected results.
