### ISSUE TITLE
[Error] After upgrade to MediatR 9.0.0 : Unable to cast object of type 'System.Collections.Generic.IEnumerable'

### ISSUE THREAD

**Issue by luckyboykg** [jbogard/MediatR#590]
I build a Web API with Asp.Net Core 5.0 and everything working fine!
But when I upgrade from MediatR version 8.0.1 to 9.0.0, I get this issue:

```
Error: Unable to cast object of type 'System.Collections.Generic.IEnumerable`1[MediatR.IPipelineBehavior`2[Ettip.Domain.Queries.Admin.OfficialStoryRequest.PagingStoriesByTopicsRequest,Ettip.Domain.Queries.Responses.Admin.OfficialStoriesResponse]][]' to type 'System.Collections.Generic.IEnumerable`1[MediatR.IPipelineBehavior`2[Ettip.Domain.Queries.Admin.OfficialStoryRequest.PagingStoriesByTopicsRequest,Ettip.Domain.Queries.Responses.Admin.OfficialStoriesResponse]]' - StackTrace :    at MediatR.ServiceFactoryExtensions.GetInstances[T](ServiceFactory factory)
   at MediatR.Internal.RequestHandlerWrapperImpl`2.Handle(IRequest`1 request, CancellationToken cancellationToken, ServiceFactory serviceFactory)
   at MediatR.Mediator.Send[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Ettip.Api.Controllers.OfficialStoriesController.PagingStoriesByTopics(PagingStoriesByTopicsRequest request) in /Users/tamtang/Documents/Source Code/Ettip-Api/Ettip.Api/Controllers/OfficialStoriesController.cs:line 124
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

After I check a lot of things from MediatR's wiki and search this issue from Google but I found nothing.
Finally, I have to revert my Web API to MediatR version 8.0.1 to make my Web API working again.

Does anyone know any clues to resolve this issue?

Here is my code
```
 public async Task<IActionResult> PagingStoriesByTopics(PagingStoriesByTopicsRequest request)
        {
            var result = await _mediator.Send(request);
       }

 public class PagingStoriesByTopicsRequest : IRequest<OfficialStoriesResponse>
    {
        public List<int> TopicIds { get; set; }
        public List<Guid> AuthorIds { get; set; }
        public int PageSize { get; set; }
        public int PageIndex { get; set; }
        public string OrderBy { get; set; }
        public string ThenBy { get; set; }
    }

public class OfficialStoriesResponse 
    {
        public List<OfficialStoryModel> Data { get; set; }
        public bool CanPrev { get; set; }
        public bool CanNext { get; set; }
    }

 public async Task<OfficialStoriesResponse> Handle(PagingStoriesByTopicsRequest message,
            CancellationToken cancellationToken)
        {
             //The request could not come here after it was sent
        }
```

**Comment by pathfinder8008** [comment]
Almost identical problem here.  Did you ever solve this problem?

**Comment by luckyboykg** [comment]
Today, I come back to this issue and I find out I made a very old configuration when adding MediatR on the startup file (but it's still working on MediatR 8.0.1)

Just **remove these lines** (if you already have them) on the startup file (when we add MediatR).
I got this issue because I was set up this project from the time .NET Core 1.0 was released (more than 5 years ago ^^)

            services.AddScoped<IMediator, Mediator>();
            services.AddTransient<ServiceFactory>(sp => sp.GetService);
            services.AddTransient<ServiceFactory>(sp => sp.GetServices);

Here is the change from my project.

![image](https://user-images.githubusercontent.com/7939156/156877466-a67db3db-aab5-4969-b170-1b3f4685deb5.png)

Hopefully, I can help you @pathfinder8008
