### ISSUE TITLE
Blazor WebAssembly lazy load with MediatR 

### ISSUE THREAD

**Issue by CyberBizSoft** [jbogard/MediatR#658]
Blazor WebAssembly
.Net 5.0
MediatR 9.0.0
MediatR.Extensions.Microsoft.DependencyInjection 9.0.0

           builder.Services.AddMediatR(typeof(Program),
                                       typeof(FullLayout),
                                       typeof(SettingsHomePage));  // This assembly is lazy loaded

============================================================
When I add the last assembly, I get the following exception:
============================================================
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.IO.FileNotFoundException: Could not load file or assembly 'Settings.Dashboard.View, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Settings.Dashboard.View, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<Main>d__0](<Main>d__0& stateMachine)
at Dashboard.Program.Main(String[] args)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] 
--- End of inner exception stack trace ---
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
at Microsoft.AspNetCore.Components.WebAssembly.Hosting.EntrypointInvoker.InvokeEntrypoint(String assemblyName, String[] args)

**Comment by CyberBizSoft** [comment]
BTW, I found a solution:
https://blogs.u2u.be/peter/post/blazor-lazy-loading-and-dependency-injection
