### ISSUE TITLE
RequestExceptionProcessorBehavior throws Object reference exception

### ISSUE THREAD

**Issue by epitka** [jbogard/MediatR#697]
Getting 
an error when invoking Send method

`await mediator.Send(command, cancellationToken);`

Handler gets invoked successfully and processes request without any errors, but then MediatR throws this

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Internal.RequestHandlerWrapperImpl`2.<>c.<Handle>b__0_0(Task`1 t)
```

Using aspnetcore with MediatR version 9 and registering it using extension method

`services.AddMediatR(typeof(DummyCommand).Assembly);`

**Comment by jbogard** [comment]
That method is quite large, can you use the symbols package to get at least a line number there?

**Comment by epitka** [comment]
> That method is quite large, can you use the symbols package to get at least a line number there?

Which package is that?

**Comment by jbogard** [comment]
It's a feature of Visual Studio to [debug via symbol packages](https://devblogs.microsoft.com/visualstudio/debugging-external-sources-with-visual-studio/). You can filter to only pull in MediatR, then in the "External Sources" part:
![image](https://user-images.githubusercontent.com/104498/150153145-6c9318da-fd17-4002-b9e6-71b4478471cd.png)

Open the `RequestExceptionProcessorBehavior` class you can set a breakpoint:

![image](https://user-images.githubusercontent.com/104498/150153218-0df817f6-4a9e-4f28-8744-e37736c395af.png)

And debug from there.

**Comment by epitka** [comment]
state is null

![image](https://user-images.githubusercontent.com/117607/150156372-2bbd0eba-cf6a-4b3b-9ce7-85c218b90352.png)

**Comment by jbogard** [comment]
What? How though it was instantiated two lines above, and not assigned anywhere else.

**Comment by epitka** [comment]
> What? How though it was instantiated two lines above, and not assigned anywhere else.

ooops, sorry, doing multiple things at the same time, not reached that line yet :)
