### ISSUE TITLE
System.InvalidProgramException: Common Language Runtime detected an invalid program

### ISSUE THREAD

**Issue by leniel** [jbogard/MediatR#758]
Hey guys,

I hope someone can shed some light into what may be causing this exception. This one is a mystery. It's only happening on the deployed app on Azure App Service. While debugging the app locally the code is working fine and no exception is being thrown.

This is the exception:

```
2022-07-01 15:36:31.557 +00:00 [Error] Company.API.Infrastructure.ErrorHandlingMiddleware: Error ID = 632a941d-bdea-4987-b371-46f98c33c542 @ 7/1/2022 3:36:31 PM
Error constructing handler for request of type MediatR.IRequestHandler`2[Company.Api.Controllers.Reports.Queries.GetCompletedFilesQuery,System.Collections.Generic.IEnumerable`1[Company.DTO.Reports.CompletedFilesReportResponse]]. Register your handlers with the container. See the samples in GitHub for examples.
System.InvalidOperationException: Error constructing handler for request of type MediatR.IRequestHandler`2[Company.Api.Controllers.Reports.Queries.GetCompletedFilesQuery,System.Collections.Generic.IEnumerable`1[Company.DTO.Reports.CompletedFilesReportResponse]]. Register your handlers with the container. See the samples in GitHub for examples.
 ---> System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at MediatR.ServiceFactoryExtensions.GetInstance[T](ServiceFactory factory)
   at MediatR.Wrappers.HandlerBase.GetHandler[THandler](ServiceFactory factory)
   --- End of inner exception stack trace ---
   at MediatR.Wrappers.HandlerBase.GetHandler[THandler](ServiceFactory factory)
   at MediatR.Wrappers.RequestHandlerWrapperImpl`2.<>c__DisplayClass1_0.<Handle>g__Handler|0()
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at Company.API.Controllers.Reports.ReportsController.CompletedFiles(Int32 clientId, Nullable`1 from, Nullable`1 to) in D:\a\1\s\src\Company.API\Controllers\Reports\ReportsController.cs:line 530
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Company.API.Startup.<>c.<<Configure>b__10_1>d.MoveNext() in D:\a\1\s\src\Company.API\Startup.cs:line 465
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Company.API.Infrastructure.Swagger.SwaggerBasicAuthMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Company.API\Infrastructure\Swagger\SwaggerBasicAuthMiddleware.cs:line 60
   at Company.API.Infrastructure.ErrorHandlingMiddleware.Invoke(HttpContext context, IWebHostEnvironment env, ICacheService cacheService) in D:\a\1\s\src\Company.API\Infrastructure\ErrorHandlingMiddleware.cs:line 40
```

I did a modification in which I ditched MediatR totally and the code is working fine with all the same services being passed directly to the class. Like this:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/764854/177223594-8684ae75-aec1-4bb4-8369-642ab12b20a2.png">

Any ideas about what may be causing that exception when using MediatR? The app is using .NET 6 and the latest MediatR version from NuGet:

```
<PackageReference Include="MediatR" Version="10.0.1" />
<PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="10.0.1" />
```

MediatR was being initialized like this in `Startup.cs`:

`services.AddMediatR(typeof(Startup));`

then I changed to:

`services.AddMediatR(AppDomain.CurrentDomain.GetAssemblies());`

to test if the exception would go away. The exception remained after this change.

**Comment by jbogard** [comment]
This is an exception in the MS DI container. Try testing directly against that container and not thru MediatR.
