### ISSUE TITLE
Unhandled exception. System.TypeLoadException: Could not load type 'MediatR.ServiceFactory' from assembly 'MediatR, Version=12.0.0.0, Culture=neutral, PublicKeyToken=bb9a41a5e8aaa7e2'.

### ISSUE THREAD

**Issue by ademclk** [jbogard/MediatR#848]
I have updated my MediatR to 12.0.0.0 now my application is not working.

[My project](https://github.com/ademclk/ceyehat-api)

Error while running

```
/usr/local/share/dotnet/dotnet /Users/ademclk/RiderProjects/ceyehat-api/ceyehat/bin/Debug/net7.0/ceyehat.dll
Unhandled exception. System.TypeLoadException: Could not load type 'MediatR.ServiceFactory' from assembly 'MediatR, Version=12.0.0.0, Culture=neutral, PublicKeyToken=bb9a41a5e8aaa7e2'.
   at MediatR.Registration.ServiceRegistrar.AddRequiredServices(IServiceCollection services, MediatRServiceConfiguration serviceConfiguration)
   at MediatR.ServiceCollectionExtensions.AddMediatR(IServiceCollection services, IEnumerable`1 assemblies, Action`1 configuration)
   at MediatR.ServiceCollectionExtensions.AddMediatR(IServiceCollection services, Assembly[] assemblies)
   at Ceyehat.Application.DependencyInjection.AddApplication(IServiceCollection services) in /Users/ademclk/RiderProjects/ceyehat-api/Ceyehat.Application/DependencyInjection.cs:line 12
   at Program.<Main>$(String[] args) in /Users/ademclk/RiderProjects/ceyehat-api/ceyehat/Program.cs:line 10

Process finished with exit code 134.
```

This line causes the error 
```C#
services.AddMediatR(typeof(DependencyInjection).Assembly);
```

**Comment by rude-seagull** [comment]
You have to use 

```
services.AddMediatR(cfg => {
    cfg.RegisterServicesFromAssembly(typeof(Program).Assembly);
});
```

as stated in the [migration guide](https://github.com/jbogard/MediatR/wiki/Migration-Guide-11.x-to-12.0)
