### ISSUE TITLE
System.InvalidOperationException with KeyedServices in .NET 8

### ISSUE THREAD

**Issue by kl1mm** [jbogard/MediatR#942]
Hi,
I'm currently playing with the new .NET 8 Preview 7 that came out a few days ago.

When I add a KeyedService to the DI container, it causes a System.InvalidOperationException thrown by MediatR.Registration.ServiceRegistrar.RegisterBehaviorIfImplementationsExist.

It seems that the ImplementationType property of ServiceDescriptor is accessed which is not allowed in the case of a "keyed" ServiceDescriptor.

maybe this helps to prepare MediatR for .NET8 KeyedServices?

cheers mMilk

Example to reproduce
```csharp
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddKeyedSingleton<MyService>("mykey");

// causes System.InvalidOperationException
builder.Services.AddMediatR(cfg =>
{
    cfg.RegisterServicesFromAssembly(typeof(Program).Assembly);
}); 

var app = builder.Build();

app.MapGet("/", (MyService svc) => svc.SayHello());
app.Run();

public class MyService
{
    public string SayHello() => "Hello";
}
```

> Unhandled exception. System.InvalidOperationException: This service descriptor is keyed. Your service provider may not support keyed services.
   at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.ThrowKeyedDescriptor()
   at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.get_ImplementationType()
   at MediatR.Registration.ServiceRegistrar.<>c.<RegisterBehaviorIfImplementationsExist>b__12_0(ServiceDescriptor service)
   at System.Linq.Enumerable.SelectIListIterator2.MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable1 source, Func2 predicate)
   at MediatR.Registration.ServiceRegistrar.RegisterBehaviorIfImplementationsExist(IServiceCollection services, Type behaviorType, Type subBehaviorType)
   at MediatR.Registration.ServiceRegistrar.AddRequiredServices(IServiceCollection services, MediatRServiceConfiguration serviceConfiguration)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddMediatR(IServiceCollection services, MediatRServiceConfiguration configuration)

**Comment by jbogard** [comment]
Ah just *adding* a keyed service causes this issue? That seems strange, that an accessor throws this exception.

**Comment by jbogard** [comment]
Yep, this is what broke it: https://github.com/dotnet/runtime/pull/87183/files#diff-90a4b966bf74781df1f355057ad5adca90af0211e46c659965ce745fb0594b5dR157

I don't support keyed services, so I suppose I'll have to explicitly check to see if it's a keyed service and skip them. Annoying.

**Comment by kl1mm** [comment]
Hey @jbogard,
yes it's not that MediatR supports Keyedservices but that the two can coexist in one application.

When I´m right ServiceDescriptor class has a property called IsKeyedService - maybe this helps.

mMilk

**Comment by jbogard** [comment]
Yeah that's what I'll have to do. Luckily that property is public!

**Comment by jbogard** [comment]
Realized I didn't push, give it a few minutes and it'll be RC2.

**Comment by Dulatr** [comment]
@jbogard thanks for the response!

Sorry I've never used MyGet before, what's the feed url?

**Comment by jbogard** [comment]
There's a link in the readme but you can find it here: https://myget.org/gallery/mediatr-ci

If I was motivated I probably could have put prerelease packages up on NuGet. But like I said. Motivated.

**Comment by iatsuta** [comment]
Good afternoon, is there any news on solving the problem?

**Comment by lcmassena-opt** [comment]
I am facing the same issue but more strange is: I am not using any Keyed service in my Azure Functions project.

**Comment by vineetshrivas12** [comment]
Just place MediatR  before any keyed service, it will work like the below

// causes System.InvalidOperationException
builder.Services.AddMediatR(cfg =>
{
    cfg.RegisterServicesFromAssembly(typeof(Program).Assembly);
});
builder.Services.AddKeyedSingleton<MyService>("mykey");

**Comment by adam-eichelkrautctpg** [comment]
@vineetshrivas12 this was the exact problem we had as well thank you!
